public:
  bind:
    address: 'localhost'

  services:
    allowed:
      - github
      - static-badge
      - nexus
      - sonar
      - metadata-hub

    metadataHub:
      baseUri: http://127.0.0.1:5000

  cors:
    allowedOrigin: ['http://localhost:3000']

  handleInternalErrors: false
